version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

    # expose: 
    #   - "5432"
    ports:
      - "127.0.0.1:5432:5432"
     
    volumes: 
          - ./init.sql:/docker-entrypoint-initdb.d/init.sql